### ISSUE TITLE
Sugestões de Issues da Semana 3

### ISSUE THREAD

**Issue by ofallante** [impulsonetwork/opensourcefriday#1]
## Como funciona:

- Sugira como comentário um Projeto/Issue relevante para a comunidade.
- Vote com um joinha 👍 👎  nas issues de projetos já sugeridos.

Dia 22/03 fecha a votação e os projetos mais bem votados serão escolhidos para a lista do opensourcefriday da semana.

As Issues devem ser submetidas no seguinte formato:

## [Nome do Projeto] - [Link] 
[Descrição (opcional)]
[List of Issues (opcional)]

**Comment by TryckBR** [comment]
### Module NPM img-tools

[https://www.npmjs.com/package/img-tools](url)

### Description

Module for manipulating images with various functionalities, for example resizing images, rotate photos, convert base64 to Blob, among others.

**Comment by ofallante** [comment]
## BibleAPI.co - https://github.com/ofallante/bibleapi
bibleAPI.co is a RESTful API of the Holy Bible developed with AdonisJs 🚀 

- Add Stats - https://github.com/ofallante/bibleapi/issues/21
- Add Biblical keys - https://github.com/ofallante/bibleapi/issues/6

**Comment by juuh42dias** [comment]
### Transerviços - https://gitlab.com/juuh42dias/transervicos

**Descrição**
Esse é um projeto de reescrita do projeto https://github.com/ThoughtWorksInc/transervicos que tenho trabalhado aos meus Domingos. Ainda me falta organizar algumas coisas por lá, mas qualquer coisa só me dar um ping.

**Lista de Issues**
https://gitlab.com/juuh42dias/transervicos/issues
Aqui tem algumas issues que foram "migradas" do GitHub para lá

**Comment by lhcgoncalves** [comment]
# Marinara Extension - [schmich/marinara](https://github.com/schmich/marinara)

Extensão do Chrome que habilita a técnica Pomodoro para aumentar a produtividade no trabalho.

*Lista de issues*

- Tradução para outros idiomas - [#78](https://github.com/schmich/marinara/issues/78)

**Comment by xavierleonardo** [comment]
## Sharebook - [SharebookBR](https://github.com/SharebookBR)

App livre para doar ou ganhar livros.

### Os repos estão separados em:

- [sharebook-backend](https://github.com/SharebookBR/sharebook-backend)
- [sharebook-mobile](https://github.com/SharebookBR/sharebook-mobile)
- [sharebook-frontend](https://github.com/SharebookBR/sharebook-frontend)
- [sharebook-qa](https://github.com/SharebookBR/sharebook-qa)

**Comment by lhcgoncalves** [comment]
# SOS Brumadinho - [sosbrumadinho/victims_location_prediction](https://github.com/sosbrumadinho/victims_location_prediction)

Este projeto visa implementar uma biblioteca de software para prever a localização das vítimas após a ruptura da barragem ou desastres similares.

**Lista de Issues**

Tem algumas abertas, mas o foco é em ideias e projetos que ajudem a resolver problema durante desastres. Vale a pena entrar nas discussões e gerar insights ou até mesmo novos projetos
