### ISSUE TITLE
Sugestões de Issues da Semana 4

### ISSUE THREAD

**Issue by lhcgoncalves** [impulsonetwork/opensourcefriday#2]
## Como funciona:
* Sugira como comentário um Projeto/Issue relevante para a comunidade.
* Vote com um joinha 👍 👎  nas issues de projetos já sugeridos.

Dia 29/03 fecha a votação e os projetos mais bem votados serão escolhidos para a lista do opensourcefriday da semana.

As Issues devem ser submetidas no seguinte formato:

## [Nome do Projeto] - [Link]
[Descrição (opcional)]
[Lista de Issues (opcional)]

**Comment by MaykeAlisson** [comment]
**Novo Anjo** - [https://github.com/MaykeAlisson/novoanjo](url)

**Descrição:** Novo Anjo é um sistema solidário, que visa realizar o encontro entre pessoas carentes e pessoas dispostas a ajudar, seja com alimentos, roupas, tempo (seja para ajudar em eventos, bater papo), profissionais podem prestar seus serviços de modo gratuito, entre outras atividades.  O projeto esta no inicio então toda ajuda e bem vinda, qualquer dica ou critica e de grande valia. O sistema e desenvolvido em Nodejs.

**Issues:** Como o projeto esta no inicio tem varias issues abertas, seja front end ou back end.

**Comment by Wmitrut** [comment]
**Awesome Brazilian Dev Blogs** - https://github.com/Wmitrut/awesome-brazilian-devblogs

**Descrição:** Este projeto visa compilar blogs de desenvolvedores da comunidade brasileira. A exigência principal é que o blog esteja ou tenha uma quantia considerável de posts em português PT-BR.

**Issues:** Não possui. Porém é uma boa maneira de aprender a contribuir e fazer seus primeiros pull-requests, além é claro, de divulgar seu blog nessa lista que tem crescido todos os dias :D

**Comment by ofallante** [comment]
**rscss-pt-br** - https://github.com/rbezerra/rscss-pt-br

**Descrição:** Sistema Razoável para Estrutura de Arquivos CSS. Um conjunto de simples ideias para guiar seu processo de construir arquivos CSS de fácil manutenção

**Issues:** Ainda não possui.
